### ISSUE TITLE
Firefox compatibility?

### ISSUE THREAD

**Issue by ZyrkRan** [Adriani6/SpigotNotifier#10]
Title is self-explanatory.

I would love to use this in Firefox.

**Comment by Adriani6** [comment]
Thanks for your interest, I'm currently short in time however once I'm done with exams I will port it over to Firefox and Opera. Unfortunately I don't have enough time to work on it at the moment.

**Comment by ZyrkRan** [comment]
Sounds good! Hope to hear more about this app soon!
