### ISSUE TITLE
How can i translate source code and import it?

### ISSUE THREAD

**Issue by rplcnn** [Adriani6/SpigotNotifier#11]
How can i translate source code and import it?

**Comment by Adriani6** [comment]
Translate source code? Not quite understand what you mean. 

By import you mean pull? It's exactly like any other repository.

**Comment by rplcnn** [comment]
yeap, i just wanna translate and use for turkish minecraft forums. may i?

**Comment by rplcnn** [comment]
great extension by the way

**Comment by Adriani6** [comment]
Of course. The the extension is open source, you're free to modify it as you like, however I wouldn't mind some credit on it (link to repo for example) if possible.
Thanks! Glad you like it.

Just so you know before you modify it, there will also be an update coming out soon, by Tuesday with some minor changes (which will not really affect anything in particular to the user) and next week with additional features.

**Comment by rplcnn** [comment]
Sure. I will.

**Comment by rplcnn** [comment]
Do I have to 5$ google developer thing to share?

**Comment by rplcnn** [comment]
or just send files to you?

**Comment by Adriani6** [comment]
If you want to host your app on Google Web Store, then you pay $5 to Google for hosting your project.
Unfortunately, I will not host it for you as because I don't have the time to check the project source etc.
