### ISSUE TITLE
[Feature] Don't show an alerts for the next x minutes

### ISSUE THREAD

**Issue by MiniDigger** [Adriani6/SpigotNotifier#12]
I got a feature request. Add a feature to don't show an alert for the next x minutes. could be useful for meetings, screen sharing session or to just boost your productivity.

**Comment by Adriani6** [comment]
I'm working on a new update, so is Scuffy. We will add it in the coming updates.

**Comment by Dooleylabs** [comment]
An addition to this: recently, the extension has begun sending notifications every 5 minutes if an alert is available. This is greatly annoying, as it used to only send a notification every time there was a new alert to be viewed. If it's possible, please restore this capability. Until then, I must disable the extension's notifications as they've been annoying me greatly.

**Comment by Adriani6** [comment]
Can't replicate. The way this system checks there's no way it could send two of the same notifications unless there has been two new notifications added on Spigot.

It doesn't have 5 minute intervals either. It's impossible it does that. Something must be wrong on your end.

**Comment by Adriani6** [comment]
Added ability to 'mute' intervals in 2.0.
