### ISSUE TITLE
Alert spam after adding extension

### ISSUE THREAD

**Issue by Cldfire** [Adriani6/SpigotNotifier#14]
Right after loading the extension (first check of the alerts page), I got spammed with alerts for every notification on the page (it thought they were all new). 

Not sure what the best way to resolve this would be, but perhaps checking for the asterisk that marks recent new alerts would be helpful?

![2016-08-20 22_36_27-latest alerts _ spigotmc - high performance minecraft](https://cloud.githubusercontent.com/assets/13814214/17834998/cb2074d4-6726-11e6-8ab2-a259c121f5fd.png)

![2016-08-20 22_38_48-latest alerts _ spigotmc - high performance minecraft](https://cloud.githubusercontent.com/assets/13814214/17835001/e5de0c1e-6726-11e6-8a21-b7f5788b41c8.png)

**Comment by Adriani6** [comment]
I know of this, I did not know about the asterisk, hard to know when I'm not bombarded with notifications making it harder to test ;p

**Comment by Adriani6** [comment]
Fixed with 1.8.1
