### ISSUE TITLE
An option to have discreet non spammy notifications.

### ISSUE THREAD

**Issue by SilverCory** [Adriani6/SpigotNotifier#16]
I liked the older version where it didn't have all the thread information, it just had the number of new alerts. Is it also possible to clear and refresh the notifications also rather than have them all stack so next time you open chrome it spams you with all 40 new notifications.

**Comment by Adriani6** [comment]
I'll add an option to choose a mode I suppose in the next update.

**Comment by Adriani6** [comment]
Fixed with above commit. The spam should no longer be coming through but a single message if you have more than 1 notification waiting.
