### ISSUE TITLE
Add a link to the packaged plugin on the Chrome Web Store

### ISSUE THREAD

**Issue by zachbr** [Adriani6/SpigotNotifier#3]
Don't think this warrants a PR. But a link would be nice. Either in the readme or in the repo description at the top of the page. Or both :D

**Comment by Adriani6** [comment]
Added links to Google Web Store.
Will update Readme soon.

**Comment by ScruffyRules** [comment]
I can update the readme with the new options panel @Cldfire and I are working on. :tongue:
